version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./swagger.json:/app/swagger.json
